---
title: "NYC Restaurant Inspection"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: flatly
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(plotly)
library(p8105.datasets)
```

```{r}
data("rest_inspec")

tidy_rest_inspec = rest_inspec |>
  filter(grade %in% c("A", "B", "C"), boro != "Missing") |>
  mutate(boro = str_to_title(boro),
         dba = str_to_upper(dba)) |>
  mutate(cuisine_description = recode(
    cuisine_description,
    "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" = "Latin",
    "Bottled beverages, including water, sodas, juices, etc." = "Bottled Beverages",
    "Café/Coffee/Tea" = "Coffee/Tea"
  )) |>
  select(boro, critical_flag, cuisine_description, dba, score, violation_code, zipcode, grade)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Distribution of Scores for Grade "C" Restaurants by Cuisine Description and Borough

```{r}
tidy_rest_inspec |>
  filter(grade == "C") |>
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) |>
  plot_ly(x = ~cuisine_description, y = ~score, color = ~boro, type = "box", 
          width = 800, height = 400, colors = "viridis") |>
  layout(yaxis = list(title = "Score"),
         xaxis = list(title = "Cuisine Description",
                      tickfont = list(size = 8)))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Restaurant Scores for Top 10 Cuisine Descriptions and Boroughs 

```{r}
top_cuisines = tidy_rest_inspec |>
  group_by(cuisine_description) |>
  summarise(count = n_distinct(dba)) |>
  arrange(desc(count)) |>
  head(10)

# Filter `tidy_rest_inspec` to include only the top 10 cuisine descriptions
filtered_data = tidy_rest_inspec |>
  filter(cuisine_description %in% top_cuisines$cuisine_description)

# Create a scatter plot with color differentiation by borough
filtered_data |>
  mutate(text_label = str_c("Restaurant:", dba, "\nGrade:", grade, "\nCritical Flag:", critical_flag)) |>
  plot_ly(
    x = ~cuisine_description, y = ~score, type = "scatter", mode = "markers", 
    color = ~boro, text = ~text_label, alpha = 0.5, colors = "viridis", opacity = 0.8) |>
  layout(
    xaxis = list(title = "Cuisine Description"),
    yaxis = list(title = "Score")
  )
```

### Unique Restaurant Counts by Borough and Grade

```{r}
tidy_rest_inspec |>
  distinct(boro, dba, grade) |>
  group_by(boro, grade) |>
  count(grade) |>
  mutate(grade, fct_reorder(grade, n)) |>
  plot_ly(x = ~grade, y = ~n, color = ~boro, type = "bar", colors = "viridis") |>
  layout(yaxis = list(title = "Count of Restaurants"),
         xaxis = list(title = "Grade"))
```

