---
title: "Plotly"
author: "Hyun Jin Jung"
date: "2023-10-30"
output: html_document
---

```{r, include = FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)

data("rest_inspec")
```

We will be using `NYC Restaurant Inspections` dataset to make plots.

```{r}
tidy_rest_inspec = rest_inspec |>
  filter(grade %in% c("A", "B", "C"), boro != "Missing") |>
  mutate(boro = str_to_title(boro),
         dba = str_to_upper(dba)) |>
  select(boro, critical_flag, cuisine_description, dba, score, violation_code, zipcode, grade)
```

Let's make a box plot!
```{r}
tidy_rest_inspec |>
  filter(grade == "C") |>
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) |>
  plot_ly(x = ~cuisine_description, y = ~score, color = ~boro, type = "box", colors = "viridis")
```


Let's make a box plot!
```{r}
tidy_rest_inspec |>
  group_by(boro, grade) |>
  count(grade) |>
  mutate(grade, fct_reorder(grade, n)) |>
  plot_ly(x = ~grade, y = ~n, color = ~boro, type = "bar", colors = "viridis") |>
  layout(yaxis = list(title = "Count of Restaurants"),
         xaxis = list(title = "Grade"))
```

Let's make a scatter plot!
```{r}
tidy_rest_inspec |>
  mutate(text_label = str_c("Grade:", grade, "/nCritical Flag:", critical_flag)) |>
  plot_ly(
    x = ~ cuisine_description, y = ~score, type = "scatter", mode = "markers",
    color = ~boro, text = ~text_label, alpha = 0.5
  )
```

